require("options")
require("keymaps")
require("plugins-setup")

require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.cmp")
require("plugins.colorscheme")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.treesitter")

require("plugins.lsp.lspconfig")
require("plugins.lsp.mason")
require("plugins.lsp.null-ls")
